##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
url: https://gpark47.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
baseurl: /filmhistory-gh
# location of code, the full url to your github repository
source-code: https://github.com/gpark47/filmhistory-gh

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Korean History through Film 
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: A Resource of the University of British Columbia's Asian Library
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "The Korean History through Film resource was created - "
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: UBC Asian Library

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: historyfilmsfeb

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
organization-name: "UBC Asian Library"
organization-link: https://asian.library.ubc.ca/
organization-logo-banner: ubc-banner.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png



##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code. See docs/google.md
#
# Add your google-analytics-id to automatically add the embed code, e.g. "UA-76328753-1"
# google-analytics-id:
# to populate a Google CSE add the id, e.g. "002151703305773322890:1pu3smhw1t8"
# google-cse-id: 

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
